version: '3.8'

networks:
  pongy:
    ipam:
      driver: default
      config:
          - subnet: "13.37.0.0/16"

services:
  db:
      container_name: postgres
      image: postgres:13
      ports:
        - 5434:5432 #host:container
      env_file:
        - .env
      networks:
        - pongy
      restart: always

  frontend:
      build: ./frontend
      container_name: frontend
      image: frontend
      env_file:
        - ./frontend/code/.env.local
      networks:
        - pongy
      depends_on:
        - backend
      ports:
        - 3001:3001 #host:container
      restart: always

  backend:
      build: ./backend
      container_name: backend
      image: backend
      env_file:
        - ./backend/code/.env
      networks:
        - pongy
      depends_on:
        - db
      ports:
        - 3000:3000 #host:container
        - 5555:5555
        - 3004:3004
        - 3003:3003
        - 3030:3030
      restart: always