version: '3.8'

networks:
  pongy:

services:
  dev-db:
    container_name: postgres
    image: postgres:13
    ports:
      - 5434:5432 #host:container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=pong_db
    networks:
      - pongy